name: ntpp-oracle  
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:  
  - python=3.11
  - ipywidgets==8.1.7
  - joblib==1.5.2
  - jupyter==1.1.1
  - matplotlib==3.10.6
  - numpy==2.3.3
  - pandas==2.3.2
  - scipy==1.16.2
  - seaborn==0.13.2
  - requests==2.32.5
  - tqdm==4.67.1
  - urllib3==2.5.0
  - scikit-learn==1.7.2
  - spyder-kernels>=3.1
  - pytorch==2.8.0
  - pytorch-lightning==2.5.5
  - comet-ml==3.52.1
  - pip
  - pip:
    - setuptools==78.1.1
    - sacred==0.8.7
    - wandb==0.22.0
    - tensorboard==2.20.0
#    - cudatoolkit==11.3
